services:
  - type: web
    name: bloodbank
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn bloodbank.wsgi:application"
    region: us
