services:
  - type: web
    name: bloodbank
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn bloodbank.wsgi:application"
    region: us
