# Generated by Django 4.2.10 on 2024-03-29 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqno', models.IntegerField()),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('pphone', models.CharField(max_length=50)),
                ('bg', models.CharField(max_length=50)),
                ('reqdate', models.DateField()),
                ('did', models.IntegerField()),
                ('dname', models.CharField(max_length=50)),
                ('dphone', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=150)),
                ('status', models.CharField(default='New Request', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='directrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqno', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('bg', models.CharField(max_length=50)),
                ('rdate', models.DateField()),
                ('details', models.CharField(max_length=150)),
                ('nofb', models.IntegerField()),
                ('status', models.CharField(default='New Request', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='doner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('bgroup', models.CharField(max_length=20)),
                ('ldate', models.DateField()),
                ('allergy', models.CharField(default='Nil', max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('uname', models.CharField(max_length=100)),
                ('pword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('doner', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('pdate', models.DateField()),
                ('ptime', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=100)),
                ('pword', models.CharField(max_length=100)),
                ('rights', models.CharField(default='user', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgroup', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
