# Generated by Django 4.2.10 on 2024-03-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='rights',
            field=models.CharField(default='New Doner', max_length=20),
        ),
    ]
