# Generated by Django 4.2.10 on 2024-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doner_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='status',
            field=models.CharField(default='Active', max_length=25),
        ),
    ]
