# Generated by Django 4.2.10 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doner',
        ),
        migrations.AddField(
            model_name='feedback',
            name='did',
            field=models.IntegerField(default=1),
        ),
    ]
