# Generated by Django 3.2.25 on 2024-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_feedback_did_alter_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
