# Generated by Django 3.2.25 on 2024-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_patient_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='city x', max_length=100),
            preserve_default=False,
        ),
    ]
