# Generated by Django 3.2.25 on 2024-04-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_patient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(default='city x', max_length=40),
            preserve_default=False,
        ),
    ]
